# Generated by Django 3.0.3 on 2020-02-21 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_gmurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemesSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupme_url', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Meme',
        ),
    ]
